package service

import (
	"catalog-service/internal/broker"
	"catalog-service/internal/dto"
	"catalog-service/internal/models"
	"catalog-service/internal/repository"
	"catalog-service/internal/validation"
	"context"
	"regexp"
)

type SchedulesService interface {
	GetByID(id uint) (*models.SpecialistSchedule, error)

	CreateSchedules(c context.Context, id uint, req dto.ScheduleCreateRequest) (*models.SpecialistSchedule, error)

	UpdateSchedules(c context.Context, id uint, req dto.ScheduleUpdateRequest) (*models.SpecialistSchedule, error)

	DeleteSchedules(c context.Context, id uint) error
}

// AUTO-GENERATED BY COPILOT: lightweight producer abstraction to make schedule service tests realistic and isolated.
type eventProducer interface {
	Produce(context.Context, interface{}) error
}

// AUTO-GENERATED BY COPILOT END
type schedulesService struct {
	service   repository.SchedulesRepository
	producer  eventProducer
	validator validation.Validator
}

func NewSchedulesService(
	service repository.SchedulesRepository,
	producer *broker.Producer,
) SchedulesService {
	return &schedulesService{
		service:   service,
		producer:  producer,
		validator: validation.NewValidator(),
	}
}

var loginRegex = regexp.MustCompile(`^[a-zA-Z0-9_]+$`)

func (s *schedulesService) GetByID(id uint) (*models.SpecialistSchedule, error) {
	schedule, err := s.service.GetByID(id)
	if err != nil {
		return nil, err
	}

	return schedule, nil
}

func (s *schedulesService) CreateSchedules(c context.Context, id uint, req dto.ScheduleCreateRequest) (*models.SpecialistSchedule, error) {
	if _, err := s.service.GetByID(id); err != nil {
		return nil, err
	}
	if err := s.validator.ValidateScheduleCreate(req); err != nil {
		return nil, err
	}

	schedule := &models.SpecialistSchedule{
		SpecialistID: req.SpecialistID,
		Weekday:      req.Weekday,
		StartTime:    req.StartTime,
		EndTime:      req.EndTime,
	}

	if err := s.service.CreateSchedules(id, schedule); err != nil {
		return nil, err
	}

	if err := s.producer.Produce(context.Background(), schedule); err != nil {
		return nil, err
	}

	return schedule, nil
}

func (s *schedulesService) UpdateSchedules(c context.Context, id uint, req dto.ScheduleUpdateRequest) (*models.SpecialistSchedule, error) {
	schedule, err := s.service.GetByID(id)
	if err != nil {
		return nil, err
	}

	if req.StartTime != nil || req.EndTime != nil {
		if err := s.validator.ValidateScheduleUpdate(req, schedule.StartTime, schedule.EndTime); err != nil {
			return nil, err
		}
	}

	if req.Weekday != nil {
		schedule.Weekday = *req.Weekday
	}
	if req.StartTime != nil {
		schedule.StartTime = *req.StartTime
	}
	if req.EndTime != nil {
		schedule.EndTime = *req.EndTime
	}

	if err := s.service.UpdateSchedules(id, schedule); err != nil {
		return nil, err
	}
	if err := s.producer.Produce(context.Background(), schedule); err != nil {
		return nil, err
	}

	return schedule, nil
}

func (s *schedulesService) DeleteSchedules(c context.Context, id uint) error {
	if _, err := s.service.GetByID(id); err != nil {
		return err
	}
	if err := s.service.DeleteSchedules(id); err != nil {
		return err
	}

	if err := s.producer.Produce(context.Background(), id); err != nil {
		return err
	}

	return nil
}
